  <fieldset>
        <p class="des"> List of Some Services </p>
    <div class="image-container">
        <figure>
          <img src="images/p1.jpg" alt="Image 1" />
          
        </figure>
  
        <figure>
          <img src="images/p2.jpg" alt="Image 2" />
          
        </figure>
  
        <figure>
          <img src="images/p3.jpg" alt="Image 3"/>
          
        </figure>
  
        <figure>
          <img src="images/p4.jpg" alt="Image 4" />
          
        </figure>
      </div>
    </fieldset>